/** Stable machine-readable codes for the Auth module (returned in the standard error envelope). */
export const AuthErrorCode = {
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_ATTEMPTS_EXCEEDED: 'OTP_ATTEMPTS_EXCEEDED',
  OTP_LOCKED: 'OTP_LOCKED',
  OTP_RESEND_COOLDOWN: 'OTP_RESEND_COOLDOWN',
  OTP_SEND_LIMIT: 'OTP_SEND_LIMIT',
  OTP_RATE_LIMITED: 'OTP_RATE_LIMITED',
  SMS_DELIVERY_FAILED: 'SMS_DELIVERY_FAILED',
  SMS_NOT_CONFIGURED: 'SMS_NOT_CONFIGURED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_TYPE_MISMATCH: 'ACCOUNT_TYPE_MISMATCH',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ADMIN_LOGIN_LOCKED: 'ADMIN_LOGIN_LOCKED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
} as const;
